spring:
  datasource:
    initialize: false
    platform: postgresql
    url: jdbc:postgresql://ec2-79-125-12-48.eu-west-1.compute.amazonaws.com:5432/dbqneht7oba5sk?sslmode=require
    username: oxnzldhspqobmx
    password: ef5236c96296eb4c0b033397b4dcf5237c2c27b1b20374e44b7db14325b7de94
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level: error

